"""all new models

Revision ID: 2c4568e9e6f9
Revises: 4b49893306ee
Create Date: 2025-10-06 16:37:09.077460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4568e9e6f9'
down_revision: Union[str, Sequence[str], None] = '4b49893306ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(asdecimal=False), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'account_id', 'metric_key', 'source_id', name='uq_usage_dedupe')
    )
    op.create_index(op.f('ix_usage_records_account_id'), 'usage_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_usage_records_metric_key'), 'usage_records', ['metric_key'], unique=False)
    op.create_index(op.f('ix_usage_records_project_id'), 'usage_records', ['project_id'], unique=False)
    op.create_index('ix_usage_window', 'usage_records', ['project_id', 'account_id', 'metric_key', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_window', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_project_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_metric_key'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_account_id'), table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
