"""unique constraint on (project_id, version_label)

Revision ID: 4b49893306ee
Revises: a1ee54afd8d1
Create Date: 2025-10-06 16:14:31.321864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b49893306ee'
down_revision: Union[str, Sequence[str], None] = 'a1ee54afd8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_config_versions_project_label', 'config_versions', ['project_id', 'version_label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_config_versions_project_label', 'config_versions', type_='unique')
    # ### end Alembic commands ###
