"""baseline tables: config/subs/events/invoices/usage

Revision ID: 63ae4fdbd823
Revises: 2c4568e9e6f9
Create Date: 2025-10-07 10:24:44.473993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ae4fdbd823'
down_revision: Union[str, Sequence[str], None] = '2c4568e9e6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
